import Head from "next/head";
import { useSession, signIn, signOut } from "next-auth/react"

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Araç Kirala - CarRent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        
        <h1 className="text-5xl">test deneme</h1>
      </div>
    </div>
  );
}
