import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Araç Kirala - CarRent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
    </div>
  )
}
